spring:
  application:
    name: order-orchestrator
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  docker:
    compose:
      file: ./order-orchestrator/docker-compose.dev.yaml
      lifecycle-management: start-and-stop   # поднимает при старте, останавливает при завершении
      start:
        command: up                         # использовать `docker compose up`
        arguments: --force-recreate         # ВСЕГДА пересоздавать контейнеры
      stop:
        command: down                     # полностью закрывает контейнеры
        arguments: -v

# настройки Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui

clients:
  stub:
    base-url: ${STUB_BASE_URL:http://localhost:8081/}
    read-timeout: ${STUB_BASE_READ_TIMEOUT:20s}
    connect-timeout: ${STUB_BASE_CONNECT_TIMEOUT:20s}

task-execution:
  poller:
    poll-interval-ms: ${TASK_EXEC_POLL_INTERVAL_MS:10000}
    batch-size: ${TASK_EXEC_POLL_BATCH_SIZE:10}
    in-progress-lease-duration: ${TASK_EXEC_IN_PROGRESS_LEASE:2m}
  dispatcher:
    retry-delay: ${DISPATCHER_RETRY_DELAY:20s}
    thread-pool-size: ${DISPATCHER_THREAD_POOL_SIZE:10}
    max-attempts: ${DISPATCHER_MAX_ATEMPTS:5}
